plugin.id=yudao-module-iot-plugin-tcp
plugin.class=cn.iocoder.yudao.module.iot.plugin.tcp.config.IotTcpPlugin
plugin.version=1.0.0
plugin.provider=yudao
plugin.dependencies=
plugin.description=yudao-module-iot-plugin-tcp-1.0.0